{{- range $appName, $app := .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $appName }}-deployment
  labels:
    app: {{ $appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      containers:
        - name: {{ $appName }}-container
          image: {{ $app.image.repository }}:{{ $app.image.tag }}
          ports:
            - containerPort: {{ $app.service.port }}
          env:
            {{- range $envName, $envValue := $app.env }}
            - name: {{ $envName }}
              value: "{{ $envValue }}"
            {{- end }}
---
{{- end }}
