# Ingress Nginx configuration
ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080

# Prometheus and Grafana configuration
kube-prometheus-stack:
  grafana:
    enabled: true
    adminUser: admin
    adminPassword: lifi
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      paths:
        - path: /grafana
          pathType: Prefix
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: 'default'
            orgId: 1
            folder: ''
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kubernetes-cluster:
          gnetId: 6417
          revision: 1
          datasource: Prometheus

  prometheusOperator:
    enabled: true
