global:
  env: staging
  project: devops

ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080

apps:
  bird:
    image:
      repository: "484907518629.dkr.ecr.us-east-1.amazonaws.com/staging-devops-bird-repo"
      tag: "597de4f"
    ingress:
      enabled: true
      path: "/"
    service:
      port: 4201
    env:
      PORT: 4201
      DEFAULT_IMAGE_URL: "https://www.pokemonmillennium.net/wp-content/uploads/2015/11/missingno.png"
      BIRD_IMAGE_API_URL: "http://birdImage-service:4200" # Internal K8s service URL
      BIRD_API_BASE_URL: "https://freetestapi.com/api/v1/birds/"
  birdImage:
    image:
      repository: "484907518629.dkr.ecr.us-east-1.amazonaws.com/staging-devops-birdimage-repo"
      tag: "597de4f"
    ingress:
      enabled: false
    service:
      port: 4200
    env:
      PORT: 4200
      UNSPLASH_API_URL: "https://api.unsplash.com/search/photos"
      UNSPLASH_CLIENT_ID: "P1p3WPuRfpi7BdnG8xOrGKrRSvU1Puxc1aueUWeQVAI"
      DEFAULT_IMAGE_URL: "https://www.pokemonmillennium.net/wp-content/uploads/2015/11/missingno.png"
