# Ingress Nginx configuration
ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443

# Prometheus and Grafana configuration
prometheus:
  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      ingressClassName: "nginx"
      rules:
        - http:
            paths:
              - path: /prometheus
                pathType: Prefix
                backend:
                  service:
                    name: prometheus-server
                    port:
                      number: 80
  alertmanager:
    ingress:
      enabled: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: lifi
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    ingressClassName: "nginx"
    rules:
      - http:
          paths:
            - path: /grafana
              pathType: Prefix
              backend:
                service:
                  name: grafana
                  port:
                    number: 80
  dashboards:
    default:
      kubernetes-dashboard:
        gnetId: 6417
        revision: 1
        datasource: Prometheus