# Ingress Nginx configuration
ingress-nginx:
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
        https: 30443

# Prometheus and Grafana configuration
prometheus:
  server:
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
      paths:
        - path: /prometheus
          pathType: Prefix
      ingressClassName: "nginx"
  alertmanager:
    ingress:
      enabled: false

grafana:
  enabled: true
  adminUser: admin
  adminPassword: lifi
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
    paths:
      - path: /grafana
        pathType: Prefix
    ingressClassName: "nginx"
  dashboards:
    default:
      kubernetes-dashboard:
        gnetId: 6417
        revision: 1
        datasource: Prometheus
